services:
  - type: web
    name: preacher-panic
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: postgresql://postgres.uteqluwrvccmyqucvset:5N!u_CBidqhME3A@aws-1-eu-north-1.pooler.supabase.com:6543/postgres
